version: "3"

services:
  lamp-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_username
      MYSQL_PASSWORD: db_password
    command: ["--wait_timeout=3600"]
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
